### ISSUE TITLE
JavaMelody Alfresco plugin does not load

### ISSUE THREAD

**Issue by tomekszy** [javamelody/alfresco-javamelody#2] opened 2018-11-09 08:07 UTC
So, basically after compiling and installing Alfresco plugin to alfresco.war file (via apply_amps or alfresco_mmt) nothing happens... I see javamelody jar inside alfresco.war file, as well as other files/directories generated during amp installation, but site <myserver>/alfresco/monitoring does not work (404). No information in logs, and in Module Manager in Admin Console also nothing. My Alfresco Community version is 5.2.0. That's why I have few questions:
1) Is JavaMelody plugin supposed to work in community edition, or only with Alfresco One?
2) Maybe it should be installed in share.war, not alfresco.war?
3) I'm attaching compiled by me amp file. Perhaps something is wrong with compilation?
Than you for any help.

[alfresco-javamelody-addon-1.74.0.zip](https://github.com/javamelody/javamelody/files/2564899/alfresco-javamelody-addon-1.74.0.zip)

**Comment by evernat** [comment] 2018-11-10 15:31
1. It was tested with community edition.
2. No, just alfresco.war
3. Your amp file is correct, the same as [this one](https://repo1.maven.org/maven2/net/bull/javamelody/alfresco-javamelody-addon/1.74.0/alfresco-javamelody-addon-1.74.0.amp), except date of build.

I probably need to test with Alfresco community edition 5.2.0.

**Comment by evernat** [comment] 2018-12-29 17:30
I have tested again after downloading and installing alfresco community edition 5.2 (version 201707) on windows.
I have then stopped Alfresco and downloaded the [amp](https://repo1.maven.org/maven2/net/bull/javamelody/alfresco-javamelody-addon/1.74.0/alfresco-javamelody-addon-1.74.0.amp) to alfresco-community\amps and run alfresco-community\bin\apply_amps.bat (javamelody-core-1.74.0.jar is put inside alfresco-community\tomcat\webapps\alfresco.war\WEB-INF\lib\).
After starting Alfresco, the monitoring report is available at http://127.0.0.1:8080/alfresco/monitoring

So the issue is not reproduced.
So closing as invalid/not reproduced, sorry.
I can reopen, if you have more info to reproduce the issue.

**Closed as completed by evernat** 2018-12-29 17:30 UTC
